[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.lua-language-server]
command = "lua-language-server"

[[language]]
name = "rust"
auto-format = true

#language-server.rust-analyzer.config.check]
#ommand = "clippy"

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "gdscript"

[language-server.gdscript]
command = "nc"
args = [
  "127.0.0.1",
  "6005",
]
language-id = "gdscript"
